openapi: 3.0.1
info:
  title: FRIDA Car Insurance Policy Cards
  description:
    $ref: "./description_en.md"
  termsOfService: "https://github.com/FRIDA-official"
  contact:
    name: Vinh Hoi Le Chau
    url: "https://www.missmp.eu"
    email: vinh.lechau@missmp.eu
  version: 0.0.1
servers:
  - url: "https://test-api-impl-backend-jaxrs.herokuapp.com/v2"
    description: Staging
  - url: "https://test-api-impl-backend-jaxrs.xyz.com/v2"
    description: Production
paths:
  /policies/passes:
    $ref: paths/passes.yaml
  /policies/webhooks:
    $ref: paths/webhooks.yaml
components:
  # parameters:
  #   projectIdParam:
  #     $ref: parameters/project-id.yaml
  schemas:
    Pass:
      $ref: schemas/pass.yaml
