name: Push API specification to marketplace

on:
  push:
    branches:
      - master

jobs:
  copy-file:
    runs-on: ubuntu-latest
    container:
      image: redocly/cli
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Checkout destination repo
        uses: actions/checkout@v4
        with:
          repository: FRIDA-api/marketplace
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          path: destination-repo

      - name: Resolve yaml references
        run: redocly bundle FRIDA_claimsData.yaml --output docs/FRIDA_claimsData_full_en.yaml

      - name: Copy files
        run: |
          mkdir -p destination-repo

          cp -f docs/FRIDA_claimsData_full_en.yaml destination-repo/marketplace/src/assets/api/carclaims.yaml

          cd destination-repo

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .

          if git status | grep -q "Changes to be committed"
          then
            git commit -m "Copy api specification from claimsData-api" --allow-empty
            git push origin main
          else
            echo "No changes detected"
          fi
  push-api-spec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Push API Spec to Stoplight
        run: npx @stoplight/cli@6 push docs/FRIDA_claimsData_full_en.yaml --ci-token ${{ secrets.STOPLIGHT_API_TOKEN }}
